app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('introduce/', views.introduce, name="introduce"), 
    path('contact/', views.contact, name="contact"), 
    path('register/', views.register, name="register"),
    path('login/', views.loginPage, name="login"), 
    path('search/', views.search, name="search"), 
    path('category/', views.category, name="category"), 
    path('detail/', views.detail, name="detail"), 
    path('logout/', views.logoutPage, name="logout"), 
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('update_item/', views.updateItem, name="update_item"), 
]

sneakerlele/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]
urlpatterns +=static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
# Create your models here.
#Change form register django
#Category

class Category(models.Model):
    sub_category = models.ForeignKey('self',on_delete=models.CASCADE, related_name='sub_categories', null=True, blank=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200,null=True)
    slug = models.SlugField(max_length=200,unique=True)
    def __str__(self):
        return self.name
class CreateUserForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name','password1','password2']
        
    
class Product(models.Model):
    default_size = '36'  # Thay thế 'M' bằng giá trị mặc định mong muốn
    default_value = timezone.now()
    category = models.ManyToManyField(Category,related_name='product')
    name = models.CharField(max_length=200,null=True)
    is_discounted = models.BooleanField(default=False)
    sales_price = models.FloatField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    price = models.FloatField()
    size = models.CharField(max_length=10, choices=[ ('4','35'),('5','36'), ('6','37'), ('7','38'), ('8','39'), ('9','40'), ('10','41'), ('11','42'), ('12','43'), ('13','44') ], default=default_size)
    digital = models.BooleanField(default=False,null=True,blank=False)
    image = models.ImageField(null=True,blank=True)
    detail = models.TextField(null=True,blank=True)

    
    def get_discounted_price(self):
        discount_amount = (self.sales_price / 100) * self.price
        discounted_price = self.price - discount_amount
        return discounted_price
    def __str__(self):
        return self.name
    @property
    def ImageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
class Order(models.Model):
    customer = models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True)
    date_order = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)
    complete = models.BooleanField(default=False,null=True,blank=False)
    transaction_id = models.CharField(max_length=200,null=True)

    def __str__(self):
        return str(self.id)
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.discounted_total for item in orderitems])
        return total
    def discounted_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total_discounted for item in orderitems])
        return total
class OrderItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.SET_NULL,blank=True,null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null=True)
    quantity = models.IntegerField(default=0,null=True,blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    # Thêm trường discounted_price để lưu giá giảm giá
    discounted_price = models.FloatField(default=0)
    @property
    def discounted_total(self):
        return self.product.get_discounted_price() * self.quantity if self.product.is_discounted else self.product.price * self.quantity
    @property
    def get_total(self):
        total = self.discounted_price * self.quantity
        return total
    def get_total(self):
        total = self.product.price * self.quantity
        return total
    @property
    def get_total_discounted(self):
        if self.product.is_discounted:
            return self.quantity * self.product.get_discounted_price()
        else:
            return self.quantity * self.product.price
class ShippingAddress(models.Model):
    customer = models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null=True)
    address = models.CharField(max_length=200,null=True)
    city = models.CharField(max_length=200,null=True)
    state = models.CharField(max_length=200,null=True)
    mobile = models.CharField(max_length=200,null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address
    

    

app/templates/app/base.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!--css-->
        <link rel="stylesheet" href="{%static 'app/css/main.css' %}" />
        {% comment %} css {% endcomment %}

        <link href-"{%static 'app/css/style.css' %}" rel="stylesheet" type="text/css"/>
        {% comment %} <link href-"{%static 'app/css/main.css' %}" rel="stylesheet"type="text/css"/> {% endcomment %}
        <link href-"{%static 'app/css/all.min.css' %}" rel="stylesheet"/>
        <link href-"{%static 'app/css/owl.carousel.min.css' %}" rel="stylesheet"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% comment %} js {% endcomment %}
        
       <script type="text/javascript">
        var user='{{request.user}}'
        function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      const csrftoken = getCookie('csrftoken');
       </script>
        
        <title>Sneakerlele | {%block title%}{%endblock title%}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--Header-->
        <nav class=" navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid header" style="font-size:20px;">
              <a class="navbar-brand" href="{%url 'home'%}">
                <img src="{%static 'app/images/sneakerlele.png' %}" width="80" height="80" />
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'home'%}">
                      Home
                    </a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                       Nike
                    </a>
                    <ul class="dropdown-menu">
                      {% for i in categories  %}
                      <li><a class="dropdown-itme" href="{%url 'category'%}?category={{i.slug}}">{{i.name}}</a></li>
                      {% endfor %}
                    </ul> 
                  </li>
                  <li class="nav-item">
                    <a class="nav-link " href="{% url 'introduce' %}" aria-disabled="true">Introduce</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}" aria-disabled="true">Contact</a>
                  </li>
                </ul>
                <form class="d-flex" role="search" method= POST action = "{% url 'search' %}">
                  {% csrf_token %}
                  <input class="form-control me-2 searchs-1 " type="search" placeholder="search" aria-label="Search" name="searched">
                  <button class="btn btn-outline-success searchs" type="submit">search</button>
                </form>
              </div>

                <div class ="form-inline my-2 my-lg-0 users-lg" style = "visibility:{{user_login}}">
                  <span>Hi! {{request.user}}</span>
                  <span><a class="logout" href="{%url 'logout'%}"> Logout</a></span>
                </div> 
                
                <div class ="form-inline my-2 my-lg-0 login " style = "visibility:{{user_not_login}}">
                  <a class= "nav-link login-1" href="{%url 'login' %}">Login</a>
                </n>
                  <a class= "nav-link" href="{%url 'register' %}">Register</a>
                </div>
              
              <div class ="form-inline my-2 my-lg-0">
                
                <a href="{% url 'cart' %}"><img id="cart-icon" src="{%static 'app/images/cart.png'%}"></a>
                <p id='cart-total'>{{cartItems}}</p>
              </div>
            </div>
          </nav>
        <!--main body-->
        
        {% block video%}{%endblock video%}
        {% block New_product %} {% endblock New_product %}
        {% block banner_slider%}{%endblock banner_slider%}
        {% block Sales_product %} {% endblock Sales_product %}
        {% block banner1 %} {% endblock banner1 %}
        <!--giao dien cart-->
        {% block cart_content %} {% endblock cart_content %}
        <!--giao dien checkout-->
        {% block content_checkout %} {% endblock content_checkout %}
        {% block register%} {% endblock register%}
        {% block login%} {% endblock login%}
        {% block search%} {% endblock search%}
        {% block category%} {% endblock category%}
        {% block detail%} {% endblock detail%}
        {% block introduce%} {% endblock introduce%}
        {% block contact%}{% endblock contact%}

        <!-- Footer -->
        
<footer class="text-center text-lg-start bg-white text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    {% comment %} <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div> {% endcomment %}
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3 text-secondary"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Nike</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3 text-secondary"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3 text-secondary"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3 text-secondary"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3 text-secondary"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script script="{%static 'app/js/all.min.js' %}"></script>
    <script script="{%static 'app/js/myscript.js' %}"></script>
    <script script="{%static 'app/js/s3.js' %}"></script>
    <script script="{%static 'app/js/cart.js' %}"></script>
    <script src="{%static 'app/js/cart.js'%}"> </script> 
    </body>
</html>

app/templates/app/cart.html
{% extends 'app/base.html' %}
{% load static %}
{% block cart_content %}
<div class="row" style="width:100%">
	<div class="col-lg-12">
		<div class="box-element">

			<a  class="btn btn-outline-dark" href="{% url 'home' %}">&#x2190; Continue Shopping</a>

			<br>
			<br>
			<table class="table">
				<tr>
					<th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
					<th><h5>Total:<strong> {{order.get_cart_total}}</strong></h5></th>
					<th>
						<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
					</th>
				</tr>
			</table>

		</div>

		<br>
		<div class="box-element">
			<div class="cart-row">
				<div style="flex:2"></div>
				<div style="flex:2"><strong>Item</strong></div>
				<div style="flex:1"><strong>Size</strong></div>
				<div style="flex:1"><strong>Price</strong></div>
				<div style="flex:1"><strong>Quantity</strong></div>
				<div style="flex:1"><strong>Total</strong></div>
			</div>
			{%for item in items %}
			<div class="cart-row">
				<div style="flex:2"><img class="row-image" src="{{item.product.ImageURL}}"></div>
				<div style="flex:2"><p>{{item.product.name}}</p></div>
				<div style="flex:1"><p>
					{% csrf_token %}
					<label for="size">Size:</label>
					<select name="size">
						{% for choice in item.product.get_size_display %}
							<option value="{{ 4 }}">{{ 35}}</option>
							<option value="{{ 5 }}">{{ 36}}</option>
							<option value="{{ 6 }}">{{ 37}}</option>
							<option value="{{ 7 }}">{{ 38}}</option>
							<option value="{{ 8 }}">{{ 39}}</option>
							<option value="{{ 9 }}">{{ 40}}</option>
							<option value="{{ 10 }}">{{ 41}}</option>
							<option value="{{ 11 }}">{{ 42}}</option>
							<option value="{{ 12 }}">{{ 43}}</option>
							<option value="{{ 13 }}">{{ 44}}</option>
						{% endfor %}
					</select></p></div>
				<div style="flex:1">
					<p>
					{% if item.product.is_discounted %}
						<span style="flex:1">${{ item.discounted_price|floatformat:0 }}</span>
					{% else %}
						<span style="flex:1">${{ item.product.price }}</span>
					{% endif %}
					</p>
				</div>
				<div style="flex:1">
					<p class="quantity">{{item.quantity}}</p>
					<div class="quantity">
						<img data-product ={{item.product.id}} data-action = 'add' class="chg-quantity update-cart" src="{% static  'app/images/arrow-up.png' %}">
				
						<img data-product ={{item.product.id}} data-action = 'remove' class="chg-quantity update-cart" src="{% static  'app/images/arrow-down.png' %}">
					</div>
				</div>
				<div style="flex:1">
					<p>
						{% if item.product.is_discounted %}
                  		${% with discounted_total=item.discounted_price|floatformat:2 %}{{ discounted_total }}{% endwith %}
                		{% else %}
                  		${% with item_total=item.get_total|floatformat:2 %}{{ item_total }}{% endwith %}
                		{% endif %}
					</p>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock cart_content %}

app/templates/app/category.html
<!DOCTYPE html>
{% extends 'app/base.html' %}
{% load static%}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% block category%}
            <div class="row" style="width:100%">
                {% for product in products %}
                <div class="col-lg-3 col text-center mb-4" style="width:26%">
                    <div>
                        <div class = "box-element product">
                        <a href="{% url 'detail' %}?id={{product.id}}"><img class="thumbnail" src="{{product.ImageURL}}" ></a>
                        <h6><strong>{{product.name}}</strong></h6>
                        <hr>
                        <div class=" text-danger">
                        <h4 style="display: inline-block; float: center;"><strong>{{product.price}}$</strong></h4>
                        </div>
                        </div>
                    </div>
                </div> 
                {% endfor %}   
              </div>
              <div class="pagination mt-4">
                <span class="step-links">
                  {% if all_products.has_previous %}
                    <a href="?page_all=1">&laquo; first</a>
                    <a href="?page_all={{ all_products.previous_page_number }}">previous</a>
                  {% endif %}
              
                  <span class="current">
                    Page {{ all_products.number }} of {{ all_products.paginator.num_pages }}.
                  </span>
              
                  {% if all_products.has_next %}
                    <a href="?page_all={{ all_products.next_page_number }}">next</a>
                    <a href="?page_all={{ all_products.paginator.num_pages }}">last &raquo;</a>
                  {% endif %}
                </span>
              </div>
        {% endblock category%}
    </body>
</html>

app/templates/app/checkout.html
{% extends 'app/base.html' %}
{% load static %}
{% block content_checkout %}
     <div class="row" style="width:100%">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>
					
					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
			</div>
			
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.ImageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1">
                        <p>
                            {% if item.product.is_discounted %}
                               <span> $ {{ item.discounted_total|floatformat:0 }} </span>
                            {% else %}
								<span> $ {{ item.get_total|floatformat:0 }} </span>
                            {% endif %}
                        </p>
                    </div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
                            <img data-product="{{ item.product.id }}" data-action='add' class="chg-quantity update-cart" src="{% static 'app/images/arrow-up.png' %}">
                            <img data-product="{{ item.product.id }}" data-action='remove' class="chg-quantity update-cart" src="{% static 'app/images/arrow-down.png' %}">
                        </div>
					</div>
					
				</div>
				{% endfor %}
				<h5>Items:   {{order.get_cart_items}}</h5>
				<h5>Total:   ${{order.get_cart_total}}</h5>
			</div>
		</div>
	</div>
	
{% endblock content_checkout %}

app/templates/app/detail.html
<!DOCTYPE html>
{% extends 'app/base.html' %}
{% load static%}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% block detail%}
        {% for product  in products  %}
        <div class="container mt-5 mb-5">
            <div class="row d-flex justify-content-center">
                <div class="col-md-10">
                    <div class="card">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="images p-3">
                                    <div class="text-center p-4"> <img id="main-image" src="{{product.ImageURL}}" width="250" /> </div>
                                    <!--<div class="thumbnail text-center"> <img onclick="change_image(this)" src="https://i.imgur.com/Rx7uKd0.jpg" width="70"> <img onclick="change_image(this)" src="https://i.imgur.com/Dhebu4F.jpg" width="70"> </div>-->
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="product p-4">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="d-flex align-items-center"> <i class="fa fa-long-arrow-left"></i> <span class="ml-1">Back</span> </div> <i class="fa fa-shopping-cart text-muted"></i>
                                    </div>
                                    <div class="mt-4 mb-3"> <span class="text-uppercase text-muted brand">Orianz</span>
                                        <h5 class="text-uppercase">{{product.name}}</h5>
                                        <div class="price d-flex flex-row align-items-center">
                                            {% if product.sales_price > 0 %}
                                                
                                                {% with discounted_price=product.get_discounted_price %}
                                                <h4 style="display: inline-block; float:center">{{discounted_price|floatformat:0}}$</h4>                  
                                                {% endwith %}
                                                <h4 style="color:#8B0000;">(<small style="text-decoration: line-through;display: inline-block; float:center"><strong>{{product.price|floatformat:0}}$</strong></small>)</h4>
                                            {% else %}
                                            <h4 style="display: inline-block; float:center"><strong>{{product.price|floatformat:0}}$</strong></h4>
                                            {% endif %} 
                                            {% comment %} <span class="act-price">{{product.price}}</span> {% endcomment %}
                                            <!--<div class="ml-2"> <small class="dis-price">$59</small> <span>40% OFF</span> </div>-->
                                        </div>
                                    </div>
                                    <p class="about">{{product.detail}}</p>
                                    <div class="sizes mt-5">
                                        {% comment %} <p>Size: {{ product.get_size_display }}</p> {% endcomment %}
                                        {% csrf_token %}
                                        <label for="size">Size:</label>
                                        <select name="size">
                                            {% for choice in product.get_size_display %}
                                                <option value="{{ 4 }}">{{ 35}}</option>
                                                <option value="{{ 5 }}">{{ 36}}</option>
                                                <option value="{{ 6 }}">{{ 37}}</option>
                                                <option value="{{ 7 }}">{{ 38}}</option>
                                                <option value="{{ 8 }}">{{ 39}}</option>
                                                <option value="{{ 9 }}">{{ 40}}</option>
                                                <option value="{{ 10 }}">{{ 41}}</option>
                                                <option value="{{ 11 }}">{{ 42}}</option>
                                                <option value="{{ 12 }}">{{ 43}}</option>
                                                <option value="{{ 13 }}">{{ 44}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>

                                    <div class="cart mt-4 align-items-center"> 
                                        <button data-product={{product.id}} data-action = "add" class="btn btn-danger text-uppercase mr-2 px-4 add-btn update-cart">Add to cart</button> 
                                        <i class="fa fa-heart text-muted"></i> <i class="fa fa-share-alt text-muted"></i> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endblock detail%}
    </body>
</html>

app/templates/app/search.html
<!DOCTYPE html>
{% extends 'app/base.html' %}
{% load static%}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% block search%}
        <h5> Result search for {{searched}} </5> <br/>
            <div class="row" style="width:100%">
                {% for product in keys %}
                <div class="col-lg-3 col text-center mb-4">
                    <div>
                        <div class = "box-element product">
                        <a href="{% url 'detail' %}?id={{product.id}}"><img class="thumbnail" src="{{product.ImageURL}}" ></a>
                        <h6><strong>{{product.name}}</strong></h6>
                        <hr>
                        <h4 style="display: inline-block; float: center;"><strong>{{product.price|floatformat:0}}$</strong></h4>
                        </div>
                    </div>
                </div> 
                {% endfor %}   
              </div>
        {% endblock search%}
    </body>
</html>